<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Subhadip" failures="1" tests="3" name="GroupingTest" time="37.211" errors="0" timestamp="2024-12-27T22:08:03 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verfiy_account_registration" time="4.52"/>
  <testcase classname="testCases.TC002_AccountRegistrationDiffPasswordTest" name="validate_incorrect_password_message" time="3.999"/>
  <testcase classname="testCases.TC003_ValidUserLoginTest" name="validate_valid_user_credentials" time="11.793">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_ValidUserLoginTest.validate_valid_user_credentials(TC003_ValidUserLoginTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- validate_valid_user_credentials -->
</testsuite> <!-- GroupingTest -->
