<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Subhadip" failures="1" tests="2" name="EdgeTest" time="33.13" errors="0" timestamp="2025-01-16T00:25:19 IST">
  <testcase classname="testCases.TC003_ValidUserLoginTest" name="validate_valid_user_credentials" time="12.342">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC003_ValidUserLoginTest.validate_valid_user_credentials(TC003_ValidUserLoginTest.java:56)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- validate_valid_user_credentials -->
  <testcase classname="testCases.TC002_AccountRegistrationDiffPasswordTest" name="validate_incorrect_password_message" time="7.34"/>
</testsuite> <!-- EdgeTest -->
