<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Subhadip" failures="3" tests="12" name="Data Driven Test" time="110.095" errors="0" timestamp="2025-01-16T15:06:08 IST">
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="12.424">
    <skipped/>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="13.067">
    <skipped/>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="12.834">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC004_LoginDataDrivenTest.validate_login(TC004_LoginDataDrivenTest.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="3.358">
    <skipped/>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="3.169">
    <skipped/>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="3.774">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC004_LoginDataDrivenTest.validate_login(TC004_LoginDataDrivenTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="3.761">
    <skipped/>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="3.918">
    <skipped/>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="4.09">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC004_LoginDataDrivenTest.validate_login(TC004_LoginDataDrivenTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- validate_login -->
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="12.82"/>
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="5.041"/>
  <testcase classname="testCases.TC004_LoginDataDrivenTest" name="validate_login" time="13.203"/>
</testsuite> <!-- Data Driven Test -->
